train : 
  plot : 

    gqt2ouaw:
      slurm_id: 0
      description: "ERA5 O96, 1970-2022"

    i1r6k503:
      slurm_id: 0
      description: "ERA5 O96, 2014-2022"

    f26v9niq:
      slurm_id: 0
      description: "GEOs h512, 2014-2022"

    zyixbavw:
      slurm_id: 0
      description: "ERA5 O96 + GEORING h512, 2014-2022"